################################################################################
#Package install 
################################################################################
if("jsonlite" %in% rownames(installed.packages()) == FALSE){
  install.packages("jsonlite")}
library(jsonlite)
if("httr" %in% rownames(installed.packages()) == FALSE){
  install.packages("httr")}
library(httr)
################################################################################
#Obtaining the predictions
################################################################################
proteins_to_be_quried=c("Q5VWN6","P58468","Q15434","Q6P996","Q9H910","Q9Y520",
                        "Q9BY89","Q8TAP6") #Proteins need Uniprot d number.
accessioncodes<- paste0("acc=",paste0(proteins_to_be_quried,collapse = ","))
URL_start <- "https://mobidb.bio.unipd.it/api/download?"
Projection_attributes <- "&projection=acc,name,organism,ncbi_taxon_id,proteome,sequence,prediction-disorder-mobidb_lite.regions&format=json"
httr::GET(paste0(URL_start,accessioncodes,Projection_attributes),
          httr::timeout(10)) -> response
if (response$status_code >= 400){
  err_msg = httr::http_status(response)
  stop(err_msg); 
  paste("Error code: ", "response$status_code")}
content <- httr::content(response,as="text",encoding="UTF-8")
#content<- jsonlite::validate(content) #This is for troubleshooting
Prediction_data = jsonlite::fromJSON(content)
Prediction_data
################################################################################
#Developing a function that will test if the phosphorylation site is in a region of disorder.
################################################################################
FAM208_sequence= "MAPPAHKSILERSENVLMSPWKGKLIVQDRMLCDIALWSTYGAMIPTQLPQELDFKYVMKVSSLKKRLPE
AAFRKQNYLEEKVCFQDLCFNLYEVELSNRQGENIDKLTECIKNKQLAIIKCLEDRGFFILLTSSALLSE
PDFGGKQMGLHGLHLFRSPLSTGVKDLKVEDDISMKVIPILSTLNCALLETKKSLPEERIHPNTLVKRHF
QELYKADRSPSLSVAPQDRMKDPTFLGKLPSGFDLIPPAEKCPSESLTQLNSYFSDPSAYILEVSTALDL
LAEHPQSPCVSDGICDAGFSLVMTPDPEFLVSEAEVRKETETKKDSEEMLKAKKRVFPLSPASNLRVQPK
RKASMPHMVQSKKVNLCRPFPKRTASRADNSSDSPTTLKLVKGQFPQKRKRGAEVLTAQFVQKTKLDRKN
QEAPISKDVPVPTNAKRARKQEKSPVKTVPRAKPPVKKSPQKQRVNIVKGNENPRNRKQLQPVKGETASK
LQSEISRGCQEDGISINSVQPENTTAAHNDLPENSIVNYDSQALNMLADLALSSATSSTPVSEARNLHCS
SELPQNDVLLSKENSLRGTSDHEYHRGVKTQKGELLPNPSSDRKSNSGSDLTVSQDEESLVPCSQAPAKA
QSALTEEMLESSDASQSSSVSVEHSYALLLTEHSKKHLQEREILSPLFPRNGTKSPEAATPVGKVMPFRH
QPGLLLQQKPPDDPVVKPKDRPPSARVKKSSCSRIVLSCDDSVKITFKCETEYAFSLDSKYTNNPLEKTV
VRALHGPWNTDLPDNVEEVKLLLHMWVALFYSNQNKIIRSSRKVVEHSNPAKYVSINSTLESCELREIEE
SLGLEKCSADSLLETNEISRAHAAEVSFRDPNCLLPFIKTPLTQGLELCVQNEQKKTFARECDPDTQEDQ
NFICSYNNEVTGEEAKQESLETSNLVLSGIGSTQTNGPSVPSEEEIVQPLDSTRVASYSGTVTQATFTRT
YDGPGSQPVICQSSVYGTLENKVDILDAAVQTKTGTLQDLIQHGSPINNECHPSLERKDDNMGCAVINPE
PITLTFEKNAHVPIQTEGVNTADERTTFKKELIKQVSPAASLRHPVSTSENARTQGLRDIPSLVVAGQKG
TKYLCASSVGGETLDKAVCSLQKETPLPVSLPSDKTMVMEALSLAKSSSHLSPSEEVRCTQDFLSQTQSL
LGLSSEGLLELTQVEVDSSSASTTLGRQCSLNCISSGCHTSGDSLELRKNHKNGPNTENMNLEAFDSVFI
KQTSLSVSREVSLELSEEDSDIDLALTISPPTSPREEMPAGEIEQFEEAPFSNLELQDVAEEIGEPEEVA
LTESREVSSADNVSVYPSVSEEPVENKERKGDNLQPVTLILSKENCTLEIAEEINVTSDFPFDSVIEEVS
PASSPEPPVPVKETRPYQAVTPCILKLHGTQCEKSNQISQCESEDLGITEKENVFVGPTHPVGQDNFTQV
QQMQVSAEMPLILTDHPGRTGRPTLPGKVTEEIVSSEHDEGLSFSGKVQCYGRELNQPASAAKCTGDFSP
SPEKLVKSGNPLQPVSIENRNLDLKHLVLESSEPPFGPRNVIENKSLSDTLVSTTAPSGIVNVSVKQQTS
PKSSQNHLFPGDLKTDEGIYLQVKSLTAASVDGAYSTQGCMCSVVPTLCSSSDNATLTHYVRPINAEPVF
QAQEIPAGRMASLLKNGEPEAELHKETTGPGTAGPQSNTTSSLKGERKAIHTLQDVSTCETKELLNVGVS
SLCAGPYQNTADTKENLSKEPLASFVSESFDTSVCGIATEHVEIENSGEGLRAEAGSETLGRDGEVGVNS
DMHYELSGDSDLDLLGDCRNPRLDLEDSYTLRGSYTRKKDVPTDGYESSLNFHNNNQEDWGCSSWVPGME
TSLPPGHWTAAVKKEEKCVPPYVQIRDLHGILRTYANFSITKELKDTMRTSHGLRRHPSFSANCGLPSSW
TSTWQVADDLTQNTLDLEYLRFAHKLKQTIKNGDSQHSASSANVFPKESPTQISIGAFPSTKISEAPFLH
PAPRSRSPLLVTVVESDPRPQGQPRRGYTASSLDSSSSWRERCSHNRDLRNSQRNHTVSFHLNKLKYNST
VKESRNDISLILNEYAEFNKVMKNSNQFIFQDKELNDVSGEATAQEMYLPFPGRSASYEDIIIDVCTNLH
VKLRSVVKEACKSTFLFYLVETEDKSFFVRTKNLLRKGGHTEIEPQHFCQAFHRENDTLIIIIRNEDISS
HLHQIPSLLKLKHFPSVIFAGVDSPGDVLDHTYQELFRAGGFVISDDKILEAVTLVQLKEIIKILEKLNG
NGRWKWLLHYRENKKLKEDERVDSTAHKKNIMLKSFQSANIIELLHYHQCDSRSSTKAEILKCLLNLQIQ
HIDARFAVLLTDKPTIPREVFENSGILVTDVNNFIENIEKIAAPFRSSYW"
test_phosphorylation_site= 1746
Prediction_matrix= Prediction_data$`prediction-disorder-mobidb_lite`[3,1]
Prediction_matrix= as.data.frame(Prediction_matrix)
In_region_of_disorder= F
for(i < nrow(Prediction_matrix)){
  if(Prediction_matrix[i,1]< test_phosphorylation_site && 
     Prediction_matrix[i,2]){In_region_of_disorder= F}}






Prediction_data$`prediction-disorder-mobidb_lite`[3,1]
